apiVersion: v1
kind: Service
metadata:
  name: my-nginx-svc
  labels:
    app: nginx
spec:
  type: LoadBalancer
  ports:
  - name: one
    port: 8080
  - name: two
    port: 8081
  - name: three
    port: 8082
  - name: four
    port: 8083
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: jaegertracing/example-hotrod:latest
        ports:
        - name: one
          containerPort: 8080
        - name: two
          containerPort: 8081
        - name: three
          containerPort: 8082
        - name: four
          containerPort: 8083
        env:
          - name: JAEGER_AGENT_HOST
            value: "jaeger"
          - name: JAEGER_AGENT_PORT
            value: "6831"
