apiVersion: v1
kind: Service
metadata:
  name: app-db2
  labels:
    app: db2
spec:
  ports:
  - port: 5000
  selector:
    app: db2
---
apiVersion: v1
kind: Service
metadata:
  name: trace-db2
spec:
  ports:
    - port: 8000
      targetPort: 8000
      name: zero
    - port: 8081
      targetPort: 8081
      name: one
    - port: 8082
      targetPort: 8082
      name: two
    - port: 8083
      targetPort: 8083
      name: three
  selector:
    app: db2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db2
  labels:
    app: db2
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db2
  template:
    metadata:
      labels:
        app: db2
    spec:
      containers:
      - name: db2
        image: stephenfrench9/db2:prod
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        - containerPort: 8000
        - containerPort: 8001
        - containerPort: 8002
        - containerPort: 8003
