apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    app: ape
spec:
  type: LoadBalancer
  ports:
  - port: 5000
  selector:
    app: ape
---
apiVersion: v1
kind: Service
metadata:
  name: app-trace
spec:
  ports:
    - port: 8000
      targetPort: 8000
      name: zero
    - port: 8081
      targetPort: 8081
      name: one
    - port: 8082
      targetPort: 8082
      name: two
    - port: 8083
      targetPort: 8083
      name: three
  selector:
    app: ape
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: ape
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ape
  template:
    metadata:
      labels:
        app: ape
    spec:
      containers:
      - name: ape
        image: stephenfrench9/shark:1.0
        ports:
        - containerPort: 5000
        - containerPort: 8000
        - containerPort: 8001
        - containerPort: 8002
        - containerPort: 8003
