apiVersion: v1
kind: Service
metadata:
  name: app-front
  labels:
    app: ape-front
spec:
  type: LoadBalancer
  ports:
  - port: 5000
  selector:
    app: ape-front
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
  labels:
    app: ape-front
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ape-front
  template:
    metadata:
      labels:
        app: ape-front
    spec:
      containers:
      - name: ape-front
        image: stephenfrench9/front:prod
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
