apiVersion: v1
kind: Service
metadata:
  name: app-model
spec:
  ports:
  - port: 5000
  selector:
    app: model
---
apiVersion: v1
kind: Service
metadata:
  name: trace-model
spec:
  ports:
    - port: 8000
      targetPort: 8000
      name: zero
    - port: 8081
      targetPort: 8081
      name: one
    - port: 8082
      targetPort: 8082
      name: two
    - port: 8083
      targetPort: 8083
      name: three
  selector:
    app: model
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: model
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model
  template:
    metadata:
      labels:
        app: model
    spec:
      containers:
      - name: model
        image: stephenfrench9/model:prod
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        - containerPort: 8000
        - containerPort: 8001
        - containerPort: 8002
        - containerPort: 8003
